Python 2.6.5 (r265:79063, Apr 16 2010, 13:09:56) 
[GCC 4.4.3] on linux2
Type "copyright", "credits" or "license()" for more information.

    ****************************************************************
    Personal firewall software may warn about the connection IDLE
    makes to its subprocess using this computer's internal loopback
    interface.  This connection is not visible on any external
    interface and no data is sent to or received from the Internet.
    ****************************************************************
    
IDLE 2.6.5      
>>> ================================ RESTART ================================
>>> 
51
10
8
25
['one', 'two', 'three', 'four']
72
----------------------------------------------------
>>> ================================ RESTART ================================
>>> 
51
10
8
25
['one', 'two', 'three', 'four']
72
----------------------------------------------------
1
2
3
>>> ================================ RESTART ================================
>>> 
51
10
8
25
['one', 'two', 'three', 'four']
72
----------------------------------------------------
1
2
3
4
5
6
7
8
9
10
11
12
>>> ================================ RESTART ================================
>>> 
51
10
8
25
['one', 'two', 'three', 'four']
72
----------------------------------------------------
12
11
10
9
8
7
6
5
4
3
2
1
>>> ================================ RESTART ================================
>>> 
enter a:4
4
16
>>> ================================ RESTART ================================
>>> 
enter a:
>>> ================================ RESTART ================================
>>> 

>>> ================================ RESTART ================================
>>> 

>>> ================================ RESTART ================================
>>> 

>>> ================================ RESTART ================================
>>> 

>>> ================================ RESTART ================================
>>> 
